spring:
  application:
    name: Notification-Services

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            use:
              type:
                headers: false
            value:
              default:
                type: java.util.HashMap

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

server:
  port: 8085

management:
  endpoint:
    web:
      exposure:
        include: health,info


